### ISSUE TITLE
SSL certificate on your demo site

### ISSUE THREAD

**Issue by ZB-Block-JamesC** [sandinmyjoints/whatsmyua#10]
Could the security certificate on your site be updated? I'm not getting results from your API when I drop the query back to http:// -- either your API requires https:// or my host won't let me send a non-SSL request to you. :/

**Comment by sandinmyjoints** [comment]
Fixed! Thanks for the request.

**Comment by ZB-Block-JamesC** [comment]
*ping* The certificate is expired again.

**Comment by sandinmyjoints** [comment]
Fixed!
