### ISSUE TITLE
whatsmyua.info has been down for a few days

### ISSUE THREAD

**Issue by mackaaij** [sandinmyjoints/whatsmyua#19]
The homepage reports:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by sandinmyjoints** [comment]
Sorry, it is back up now!

**Comment by mackaaij** [comment]
That was quick, great! I couldn't find you at first, maybe add a link to this repository on the homepage? That way, I would have found this place sooner via Google's cache.
