### ISSUE TITLE
Broken for Microsoft Edge

### ISSUE THREAD

**Issue by michaelbutler** [sandinmyjoints/whatsmyua#3]
Hi, you are using the outdated and deprecated https://github.com/tobie/ua-parser version of the ua-parser library. This reports Edge as being Chrome, which is wrong. Please update to use https://github.com/ua-parser/uap-php where it is currently maintained and has information about new browsers (Edge, Vivaldi, et al)

**Comment by sandinmyjoints** [comment]
Thanks for flagging this. I'll update it soon.

**Comment by sandinmyjoints** [comment]
Updated, Edge is now identified. @michaelbutler
