### ISSUE TITLE
Api Problem

### ISSUE THREAD

**Issue by HeCosmin** [sandinmyjoints/whatsmyua#6]
I tried trying two link encode and default

[http://www.whatsmyua.info/api/ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/66.0.3359.181%20Safari/537.36&version=lastest](url)

[http://www.whatsmyua.info/api/ua=Mozilla/5.0 (Linux; Android 7.1.1; MI MAX 2 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36&version=lastest](url)

same two problems output!

`Cannot GET /api/ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/66.0.3359.181%20Safari/537.36&amp;version=lastest`

**Comment by sandinmyjoints** [comment]
Hi @HeCosmin , the paths in your urls are slightly wrong -- try adding `/v1` and `?ua` like so:

`http://www.whatsmyua.info/api/v1/ua?ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/66.0.3359.181%20Safari/537.36&version=lastest`

**Comment by HeCosmin** [comment]
> Hi @HeCosmin , the paths in your urls are slightly wrong -- try adding `/v1` and `?ua` like so:
> 
> `http://www.whatsmyua.info/api/v1/ua?ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/66.0.3359.181%20Safari/537.36&version=lastest`

Worked. thanks very much <3
