### ISSUE TITLE
Avoid "Mixed Content" error - enable HTTPS for http://www.whatsmyua.info

### ISSUE THREAD

**Issue by phw198** [sandinmyjoints/whatsmyua#7]
Hi @sandinmyjoints 

I'm wanting to perform a Jscript  `$_.get("http://www.whatsmyua.info/api/v1/ua")` from my GitHub Pages website, but as this is enforced with HTTPS, I get the error  
> [calling site] was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.whatsmyua.info/api/v1/ua'. This request has been blocked; the content must be served over HTTPS.

Any chance you could turn on HTTPS?

**Comment by sandinmyjoints** [comment]
@phw198 I've configured https, so you should be good to go now!
